### ISSUE TITLE
not found require 'vendor/autoload.php';

### ISSUE THREAD

**Issue by dipenpatel235** [theodhorpandeli/Stripe-Integration-Android#2]
hello..
can u please tell me how to install it ?
i think need to used composer.json

can u please paste composer.json
thanks

**Comment by theodhorpandeli** [comment]
Hello Dipen, 

You can find the required information at the Stripe's official Github repo here:
https://github.com/stripe/stripe-php/blob/master/README.md

Hope that helps,
Thanks
